import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import DefaultLayout from "../../layouts/Default";

export default function Home() {
  const router = useRouter();

  const { id } = router.query;

  const [cat, setCat] = useState(null);

  const fetchCat = async () => {
    const response = await fetch(`/api/cats/${id}`);
    const data = await response.json();
    console.log({ data: data });
    setCat(data);
  };

  console.log(cat);

  useEffect(() => {
    fetchCat();
  }, []);

  return (
    <div>
      <Head>
        <title>{id}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DefaultLayout>
        {cat && (
          <div className="container mt-5" style={{ marginLeft:"15px"}}>
            <img src={cat.image.url} />
            <div >
              <h1>{cat.name}</h1>
              <p>{cat.description} </p>
            </div>
            {/* <Link style={{position:"center"}} href="/cats">
            Back
          </Link> */}
          </div>  
        )}
        <div className="container " style={{cursor: "pointer" ,color:"blue",}}
        onClick={() => {
        router.push(`/cats`);
      }}>Back</div>
       
      </DefaultLayout>

     
    </div>
  );
}
